# Generated by Django 5.0 on 2024-01-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_address_author_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
