# Generated by Django 5.0 on 2024-01-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_book_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='published_countries',
        ),
    ]
